import { arithmeticProblemPool } from './oge6-problems.ts';
import { comparisonProblemPool } from './oge7-problems.ts';
import { expressionProblemPool } from './oge8-problems.ts';
import { equationProblemPool } from './oge9-problems.ts';
import { probabilityProblemPool } from './oge10-problems.ts';
import { functionProblemPool } from './oge11-problems.ts';
import { formulaProblemPool } from './oge12-problems.ts';
import { inequalityProblemPool } from './oge13-problems.ts';
import { sequenceProblemPool } from './oge14-problems.ts';
export const ogeAlgebraPools = { 'oge-6': arithmeticProblemPool, 'oge-7': comparisonProblemPool, 'oge-8': expressionProblemPool, 'oge-9': equationProblemPool, 'oge-10': probabilityProblemPool, 'oge-11': functionProblemPool, 'oge-12': formulaProblemPool, 'oge-13': inequalityProblemPool, 'oge-14': sequenceProblemPool };
